### ISSUE TITLE
App crashes if no GTK2 theme is available

### ISSUE THREAD

**Issue by ALEX11BR** [ALEX11BR/ThemeChanger#3]

**Comment by matteobongio** [comment]
I think I'm getting something similar, but it keeps running (with no window)

```

(.themechanger-wrapped:134850): Gtk-CRITICAL **: 20:21:28.612: gtk_tree_view_scroll_to_point: assertion 'gtk_widget_get_realized (GTK_WIDGET (tree_view))' failed

(.themechanger-wrapped:134850): Gtk-CRITICAL **: 20:21:29.824: gtk_tree_view_scroll_to_point: assertion 'gtk_widget_get_realized (GTK_WIDGET (tree_view))' failed
Traceback (most recent call last):
  File "/nix/store/ga0gzj1910mpidn24rc13f1ih2gmj3gd-python3.12-pygobject-3.50.0/lib/python3.12/site-packages/gi/overrides/Gtk.py", line 814, in _getiter
    aiter = self.get_iter(key)
            ^^^^^^^^^^^^^^^^^^
  File "/nix/store/ga0gzj1910mpidn24rc13f1ih2gmj3gd-python3.12-pygobject-3.50.0/lib/python3.12/site-packages/gi/overrides/Gtk.py", line 858, in get_iter
    raise ValueError("invalid tree path '%s'" % path)
ValueError: invalid tree path '0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/37iw5ywlgzxwrc6v21zbivjplhpig72b-themechanger-0.12.0/share/themechanger/themechanger/main.py", line 32, in do_activate
    win = ThemechangerWindow(app=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/37iw5ywlgzxwrc6v21zbivjplhpig72b-themechanger-0.12.0/share/themechanger/themechanger/window.py", line 155, in __init__
    self.gtk2SearchableThemeList = SearchableThemeList(
                                   ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/37iw5ywlgzxwrc6v21zbivjplhpig72b-themechanger-0.12.0/share/themechanger/themechanger/searchablethemelist.py", line 34, in __init__
    self.setThemesTreeViewModel(themesTreeViewModel)
  File "/nix/store/37iw5ywlgzxwrc6v21zbivjplhpig72b-themechanger-0.12.0/share/themechanger/themechanger/searchablethemelist.py", line 71, in setThemesTreeViewModel
    self.selectTheme()
  File "/nix/store/37iw5ywlgzxwrc6v21zbivjplhpig72b-themechanger-0.12.0/share/themechanger/themechanger/searchablethemelist.py", line 60, in selectTheme
    firstRow = self.themesTreeViewModelFiltered[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/nix/store/ga0gzj1910mpidn24rc13f1ih2gmj3gd-python3.12-pygobject-3.50.0/lib/python3.12/site-packages/gi/overrides/Gtk.py", line 833, in __getitem__
    aiter = self._getiter(key)
            ^^^^^^^^^^^^^^^^^^
  File "/nix/store/ga0gzj1910mpidn24rc13f1ih2gmj3gd-python3.12-pygobject-3.50.0/lib/python3.12/site-packages/gi/overrides/Gtk.py", line 816, in _getiter
    raise IndexError("could not find tree path '%s'" % key)
IndexError: could not find tree path '0'
```
